openapi: 3.0.0
info:
  title: Сервис заказов
  version: 1.0.0
paths:
  /order:
    get:
      summary: Получение всех заказов с фильтрацией по идентификатору заказа
      parameters:
        - in: header
          name: token
          description: Токен админа
          schema:
            type: string
            example: "admin_token"
        - in: query
          name: order_uid
          required: false
          schema:
            type: string
            description: Идентификатор заказа
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    order_uid:
                      type: string
                      description: Уникальный идентификатор заказа
                    track_number:
                      type: string
                      description: Трек-номер заказа
                    entry:
                      type: string
                      description: Точка входа заказа
                    delivery:
                      type: object
                      description: Информация о доставке
                      properties:
                        name:
                          type: string
                        phone:
                          type: string
                        zip:
                          type: string
                        city:
                          type: string
                        address:
                          type: string
                        region:
                          type: string
                        email:
                          type: string
                    payment:
                      type: object
                      description: Информация об оплате
                      properties:
                        transaction:
                          type: string
                        request_id:
                          type: string
                        currency:
                          type: string
                        provider:
                          type: string
                        amount:
                          type: integer
                        payment_dt:
                          type: integer
                        bank:
                          type: string
                        delivery_cost:
                          type: integer
                        goods_total:
                          type: integer
                        custom_fee:
                          type: integer
                    items:
                      type: array
                      description: Список товаров в заказе
                      items:
                        type: object
                        properties:
                          chrt_id:
                            type: integer
                          track_number:
                            type: string
                          price:
                            type: integer
                          rid:
                            type: string
                          name:
                            type: string
                          sale:
                            type: integer
                          size:
                            type: string
                          total_price:
                            type: integer
                          nm_id:
                            type: integer
                          brand:
                            type: string
                          status:
                            type: integer
                    locale:
                      type: string
                    internal_signature:
                      type: string
                    customer_id:
                      type: string
                    delivery_service:
                      type: string
                    shardkey:
                      type: string
                    sm_id:
                      type: integer
                    date_created:
                      type: string
                      format: date-time
                    oof_shard:
                      type: string
        '401':
          description: Пользователь не авторизован
        '403':
          description: Пользователь не имеет доступа
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    post:
      summary: Создание нового заказа
      parameters:
        - in: header
          name: token
          description: Токен админа
          schema:
            type: string
            example: "admin_token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order_uid:
                  type: string
                  description: Уникальный идентификатор заказа
                track_number:
                  type: string
                  description: Трек-номер заказа
                entry:
                  type: string
                  description: Точка входа заказа
                delivery:
                  type: object
                  description: Информация о доставке
                  properties:
                    name:
                      type: string
                    phone:
                      type: string
                    zip:
                      type: string
                    city:
                      type: string
                    address:
                      type: string
                    region:
                      type: string
                    email:
                      type: string
                payment:
                  type: object
                  description: Информация об оплате
                  properties:
                    transaction:
                      type: string
                    request_id:
                      type: string
                    currency:
                      type: string
                    provider:
                      type: string
                    amount:
                      type: integer
                    payment_dt:
                      type: integer
                    bank:
                      type: string
                    delivery_cost:
                      type: integer
                    goods_total:
                      type: integer
                    custom_fee:
                      type: integer
                items:
                  type: array
                  description: Список товаров в заказе
                  items:
                    type: object
                    properties:
                      chrt_id:
                        type: integer
                      track_number:
                        type: string
                      price:
                        type: integer
                      rid:
                        type: string
                      name:
                        type: string
                      sale:
                        type: integer
                      size:
                        type: string
                      total_price:
                        type: integer
                      nm_id:
                        type: integer
                      brand:
                        type: string
                      status:
                        type: integer
                locale:
                  type: string
                internal_signature:
                  type: string
                customer_id:
                  type: string
                delivery_service:
                  type: string
                shardkey:
                  type: string
                sm_id:
                  type: integer
                date_created:
                  type: string
                  format: date-time
                oof_shard:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_uid:
                    type: string
                    description: Уникальный идентификатор созданного заказа
        '400':
          description: Некорректные данные
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Пользователь не авторизован
        '403':
          description: Пользователь не имеет доступа
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
